version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: run tests
          command: python -m unittest discover --pattern=*.py -v
